### ISSUE TITLE
Monorepo scaling: lines of code?

### ISSUE THREAD

**Issue by tazle** [joelparkerhenderson/monorepo-vs-polyrepo#7]
Is the unit right for the "lines of code" metric at https://github.com/joelparkerhenderson/monorepo-vs-polyrepo#monorepo-scaling-metrics?

My gut feeling is that 1M-10M lines of code might indeed have problems in monorepo, but 1k-10k seems weirdly low.

**Comment by joelparkerhenderson** [comment]
You're correct, thank you for finding this bug. I'll edit it.
